service: api-lambda-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:511546847288:table/PeliculaTabla
        - arn:aws:dynamodb:us-west-2:511546847288:table/ActorsTabla

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  crearPelicula:
    handler: src/agregarPelicula.agregarPelicula
    events:
      - httpApi:
          path: /peliculas
          method: post
  listarPelicula:
    handler: src/listarPelicula.listarPelicula
    events:
      - httpApi:
          path: /peliculas
          method: get
  obtenerPelicula:
    handler: src/obtenerPelicula.obtenerPelicula
    events:
      - httpApi:
          path: /peliculas/{id}
          method: get
  actualizarPelicula:
    handler: src/actualizarPelicula.actualizarPelicula
    events:
      - httpApi:
          path: /peliculas/{id}
          method: put
  getSwapi:
    handler: swapi/getSwapi.getSwapi
    events:
      - httpApi:
          path: /swapi/api/people/2
          method: get 
  createActor:
      handler: swapi/createActor.createActor
      events:
        - httpApi:
            path: /swapi/api/people
            method: post
  listActor:
      handler: swapi/listActor.listActor
      events:
        - httpApi:
            path: /swapi/api/people
            method: get
 
resources:
  Resources:
    PeliculaTabla:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PeliculaTabla
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    ActoresTabla:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ActorsTabla
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH